language: node_js

sudo: false

node_js:
  - 0.10

script:
  - grunt ci

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#queue-event"
    on_success: change
    on_failure: always